version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    restart: unless-stopped
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/static:/app/static
      - ./logs/nginx:/var/log/nginx  # 挂载日志目录到宿主机
    depends_on:
      - flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge